name: Nightly

on:
  schedule:
    # every night at midnight
    - cron:  '0 0 * * *'

jobs:

  instrumentation_tests:
    strategy:
      matrix:
        api-level: [21, 22, 23, 24, 25, 27, 28, 29]
      fail-fast: false
      runs-on: macOS-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.0.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest

  unit_test_and_release:
    needs: instrumentation_tests
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: run unit tests
        run: ./gradlew testDebugUnitTest testCustomExampleDebugUnitTest
