name: Pull requests

on: [pull_request]

jobs:

  staticAnalysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Static Analysis
        run: ./gradlew ktlintCheck app:lintDebug core:lintDebug custom:lintCustomexampleDebug

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build app and custom
        run: ./gradlew app:assembleDebug custom:assembleCustomexampleDebug
